### ISSUE TITLE
Understanding the working of k8s-dt-node-labeller | Panic

### ISSUE THREAD

**Issue by bitvijays** [adaptant-labs/k8s-dt-node-labeller#2]
Hello Adaptant Labs Team,

Hope you are doing well. Thank you for your support.

On executing the binary, got the below error
```
./k8s-dt-node-labeller -d
panic: no valid device tree configuration found

goroutine 1 [running]:
main.main()
        /home/username/k8s-dt-node-labeller/main.go:127 +0xeac
```

Just thought to ask, how does k8s-dt-node-labeller work internally?

Does it goes thru the `kubectl get nodes` and figure out the nodes which have GPU? or any other setup is required. For example, currently I have Jetson TX2 and Nano reporting to the master. Both are running the `nvidia-docker runtime`. However, on executing the binary, the above error occurs.

**Comment by pmundt** [comment]
Hi @bitvijays,

At present, the node labeller is expected to run at the node level directly. It has not yet been tested running within a pod, so some modification may be needed to support this.

The panic you are seeing is simply because it is unable to find the device tree mount point within the environment you are running it from. In this case, `/proc/device-tree`. Can you verify whether this exists in your environment? If not, you may need to modify your run-time to explicitly mount procfs. The alternative is under `/sys/firmware/devicetree/base`, but the procfs entry should always point here:

```
pmundt@jetson-nano:~/k8s-dt-node-labeller$ ls -la /proc/device-tree
lrwxrwxrwx 1 root root 29 Apr  7 10:48 /proc/device-tree -> /sys/firmware/devicetree/base
```

```
pmundt@jetson-nano:~/k8s-dt-node-labeller$ ./k8s-dt-node-labeller -d
Discovered the following devicetree properties:

beta.devicetree.org/nvidia-jetson-nano: 1
beta.devicetree.org/nvidia-tegra210: 1
```

In terms of how it works - it simply walks the device tree on the node upon which it is run, and applies labels for the discovered devices. You can then use these labels for node selection and pod placement.

Running anywhere in the cluster, you can then look it up as follows:
```
$ kubectl get nodes -l beta.devicetree.org/nvidia-tegra210
NAME          STATUS   ROLES    AGE   VERSION
jetson-nano   Ready    <none>   23d   v1.17.3+k3s1
```
and the full list of labels:

```
$ kubectl get nodes --show-labels jetson-nano
NAME          STATUS   ROLES    AGE   VERSION        LABELS
jetson-nano   Ready    <none>   23d   v1.17.3+k3s1   beta.devicetree.org/nvidia-jetson-nano=1,beta.devicetree.org/nvidia-tegra210=1,beta.kubernetes.io/arch=arm64,beta.kubernetes.io/instance-type=k3s,beta.kubernetes.io/os=linux,k3s.io/hostname=jetson-nano,k3s.io/internal-ip=192.168.188.91,kubernetes.io/arch=arm64,kubernetes.io/hostname=jetson-nano,kubernetes.io/os=linux,node.kubernetes.io/instance-type=k3s
```

**Comment by pmundt** [comment]
Ok, I have now gotten around to testing this within a pod and ran into the same problem, `/sys/firmware` requires privilege escalation, which I've now added to a sample daemonset deployment in 23522b9b3690b5b3ac90dd7b0c50c22ff4431506 that you can experiment with. We also needed a special service account to permit nodes to self-identify and self-label, which has been dealt with in the same.

**Comment by pmundt** [comment]
I've also taken the liberty of reworking the README with more detailed information as to the possible deployment options together with a general overview of the functionality and limitations in fafade59dac5e8f49c7c20f7283428f5e0a04382.

**Comment by bitvijays** [comment]
Thank you @pmundt :) Much appreciated for the support. :)
